---

- name: Deploy MLAG Confguration to Arista Switches
  connection: local
  hosts: S1_LEAFS
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Deploy MLAG Configuration
      import_role:
        name: roles/mlag